"""
Check which repos are missing PR #1 for Feedback from GitHub Classroom; create PR if needed

Uses PyGithub (https://github.com/PyGithub/PyGithub) as API to GitHub:

    python3 -m pip install PyGithub

PyGithub documentation: https://pygithub.readthedocs.io/en/latest/introduction.html
Other doc on PyGithub: https://www.thepythoncode.com/article/using-github-api-in-python
"""
__author__ = "Sebastian Sardina - ssardina - ssardina@gmail.com"
__copyright__ = "Copyright 2024-2025"

import csv
from argparse import ArgumentParser
import json
from pdb import main

# https://pygithub.readthedocs.io/en/latest/introduction.html
from github import Github, GithubException

import util, utils_gh
from util import (
    TIMEZONE,
    NOW_ISO,
    NOW_TXT,
    add_csv,
)
SCRIPT_NAME = "gh_pr_feedback_create"


import logging
from slogger import setup_logging
logger = setup_logging(SCRIPT_NAME, rotating_file="app.log", indent=2)
logger.setLevel(logging.INFO)  # set the level of the application logger
logging.root.setLevel(logging.WARNING)  # root logger above info: no 3rd party logs

#####################################
# LOCAL GLOBAL VARIABLES FOR SCRIPT
#####################################

# Application global variables
CSV_OUTPUT = "pr_create.csv"
CSV_HEADER = ["REPO_ID_SUFFIX", "REPO_URL", "RESULT", "DETAILS"]

PR_TITLE = "Sync Assignment"
PR_MESSAGE = """
:wave:! This pull request was automatically generated by the instructor to sync with the upstream assignment repository.

Merge this pull request to sync your assignment repository with your instructor latest changes.

If you have any questions or concerns, please contact your instructor via the forum.

Attention: @{GH_USERNAME}
"""

from github import GithubException


def sync_fork(
    repo,  # fork repo (PyGitHub object)
    repo_source,  # upstream repo (PyGitHub object)
    source_branch="main",  # branch in upstream
    target_branch="main",  # branch in fork
    create_pr=False,  # if True, create PR instead of direct update
    pr_title=PR_TITLE,
    pr_message=PR_MESSAGE,
):
    """
    Sync repo (fork) from repo_source (upstream).

    Via ChatGPT: https://chatgpt.com/s/t_69cc800eb2d881919841d4dea86a6a06
    """

    logger.info(
        f"\n🔍 Comparing {repo.full_name}:{target_branch} "
        f"with {repo_source.full_name}:{source_branch}"
    , depth=1)

    # --- Step 1: Compare (correct cross-fork comparison)
    # compare = repo_source.compare(f"{repo.owner.login}:{target_branch}", source_branch)
    commit_source = repo_source.get_branch(source_branch).commit.sha
    compare = repo.compare(target_branch, commit_source)

    logger.info(f"Status: {compare.status}", depth=1)
    logger.info(f"Behind by: {compare.behind_by}, Ahead by: {compare.ahead_by}", depth=1)

    if compare.behind_by == 0:
        logger.info("✅ Fork is already up-to-date. Nothing to do.", depth=1)
        return

    logger.info(f"⚠️ Fork is {compare.behind_by} commits behind upstream.", depth=1)

    # --- Step 2: Get latest upstream commit SHA
    source_sha = repo_source.get_branch(source_branch).commit.sha
    logger.info(f"Upstream latest SHA: {source_sha}")

    # --- Step 3: Create/update sync branch in fork
    sync_branch = f"sync-{source_branch}"

    try:
        ref = repo.get_git_ref(f"heads/{sync_branch}")
        logger.info(f"Updating existing branch {sync_branch}")
        ref.edit(source_sha, force=True)
    except GithubException:
        logger.info(f"Creating new branch {sync_branch}")
        repo.create_git_ref(ref=f"refs/heads/{sync_branch}", sha=source_sha)

    # --- Step 4: Either create PR or fast-forward
    if create_pr:
        logger.info("📬 Creating pull request...")

        try:
            pr = repo.create_pull(
                title=pr_title,
                body=pr_message.format(GH_USERNAME=repo.owner.login),
                head=sync_branch,
                base=target_branch,
            )
            logger.info(f"✅ PR created: {pr.html_url}", depth=1)

        except GithubException as e:
            logger.error(f"❌ Failed to create PR: {e}", depth=1)

    else:
        logger.info("⚡ Fast-forwarding branch directly...", depth=1)

        try:
            ref = repo.get_git_ref(f"heads/{target_branch}")
            ref.edit(source_sha, force=True)
            logger.info(f"✅ {target_branch} updated to upstream.", depth=1)

        except GithubException as e:
            logger.error(f"❌ Failed to update branch: {e}", depth=1)


if __name__ == "__main__":
    parser = ArgumentParser(description="Merge PRs in multiple repos")
    parser.add_argument("REPO_CSV", help="List of repositories to get data from.")
    parser.add_argument(
        "REPO",
        help="Source repo for the pull request (Default: %(default)s).",
    )
    parser.add_argument(
        "--branch",
        default="main",
        help="Source branch for the pull request (Default: '%(default)s').",
    )
    parser.add_argument(
        "--title", 
        type=str,
        default=PR_TITLE,
        help="Title of the pull request (Default: '%(default)s').",
    )
    parser.add_argument(
        "--repos", nargs="+", help="if given, only the repos specified will be parsed."
    )
    parser.add_argument(
        "-t",
        "--token-file",
        required=True,
        help="File containing GitHub authorization token/password.",
    )
    parser.add_argument(
        "--csv",
        action="store_true",
        default=False,
        help="Dump results into CSV files (Default: %(default)s.)",
    )
    args = parser.parse_args()
    logger.info(f"Starting on {TIMEZONE}: {NOW_ISO} - {args}")

    ###############################################
    # Filter repos as desired
    ###############################################
    list_repos = util.get_repos_from_csv(args.REPO_CSV, args.repos)
    if len(list_repos) == 0:
        logger.error(f'No repos found in the mapping file "{args.REPO_CSV}". Stopping.')
        exit(0)

    ###############################################
    # Authenticate to GitHub
    ###############################################
    if not args.token_file and not (args.user or args.password):
        logger.error("No authentication provided, quitting....")
        exit(1)
    try:
        g = utils_gh.open_gitHub(token_file=args.token_file)
    except:
        logger.error(
            "Something wrong happened during GitHub authentication. Check credentials."
        )
        exit(1)

    ###############################################
    # Process each repo in list_repos
    ###############################################

    # this is the source repo for the PRs
    repo_source = g.get_repo(args.REPO)
    commit_source = repo_source.get_branch(args.branch).commit.sha
    logger.info(f"Source repo commit SHA: {commit_source}")

    no_repos = len(list_repos)
    output_csv = []
    for k, r in enumerate(list_repos, start=1):
        repo_no = r["NO"]
        repo_id = r["REPO_ID_SUFFIX"]
        repo_name = r["REPO_ID"]
        repo_url = r["REPO_HTTP"]
        logger.info(
            f"Processing repo {k}/{no_repos}: {repo_no}:{repo_id} ({repo_url})..."
        )

        repo = g.get_repo(repo_name)    # repo to create PR into (i.e., the student repo)
        branch = "main"                 # branch in the repo


        sync_fork(
            repo,  # fork repo (PyGitHub object)
            repo_source,  # upstream repo (PyGitHub object)
            source_branch="main",  # branch in upstream
            target_branch="main",  # branch in fork
            create_pr=True,  # if True, create PR instead of direct update
        )
        exit(1)
        # compare student main branch against commit of the upstream
        """ NOTE!!!
        I tried many things with PytGithub .compare and also directly sending JSON
        request via:
        
                repo._requester.requestJsonAndCheck("GET",
                #     f"/repos/{repo.full_name}/compare/{branch}...{repo_source.owner.login}:flight-template:{args.branch}",
                # )
                # print(util.format_json(compare))
        
        it was always showing "identical", until I use the exact SHA of the upstream commit      
        """
        compare = repo.compare("main", commit_source)

        if compare.status == "identical" or compare.behind_by == 0:
            logger.info(f"Fork is already up-to-date with upstream. No PR needed. Status compares: {compare.status}")
            continue

        logger.info(f"Fork is behind upstream by {compare.ahead_by} commits. PR needed. Status compares: {compare.status}", depth=1)

        # now create the PR to sync the fork with upstream!
        try:
            print(repo.full_name)
            repo.create_pull(
                title=PR_TITLE,
                body=PR_MESSAGE.format(GH_USERNAME=repo_id),
                head=f"{repo_source.owner.login}:{args.branch}",  # source branch in upstream
                base=branch,  # branch in fork to update
            )
        except GithubException as e:
            logger.error(f"\t Exception when creating PR in repo {repo_name}: {e}")
            if e.data["message"] == "Validation Failed":
                # This should not happen anymore as we create a dummy commit in main to be able to PR into feedback
                logger.error(f"\t Perhaps no commits exist in repo.")
                output_csv.append(
                    [repo_id, repo_url, "exception_validation", e]
                )
            else:
                output_csv.append([repo_id, repo_url, "exception_create", e])
                break
            continue

        # all good! PR was created SUCCESSFULLY!
        output_csv.append([repo_id, repo_url, "created", ""])

    # print summary stats
    no_errors = len([x for x in output_csv if not x[2] in ["created"]])
    logger.info(
        f"Finished! Total repos: {no_repos} - Missing PR: {len(output_csv)} - Errors: {no_errors}."
    )

    output_csv = sorted(output_csv, key=lambda x: x[2])
    add_csv(
        CSV_OUTPUT,
        CSV_HEADER,
        output_csv,
        append=True,
        timestamp=NOW_TXT,
        quoting=csv.QUOTE_NONNUMERIC
    )

    logger.info(f"Output written to CSF file: {CSV_OUTPUT}.")

    # just for manual debug.. ouch!
    # for r in output_csv:
    #     print(r)
