"""
Sync a batch of student/team repos (forks or GitHub Classroom repos) with an upstream
source repo, by opening a "Sync Assignment" pull request in each one (or, if
create_pr=False in sync_fork(), fast-forwarding the target branch directly instead).

For each repo listed in REPO_CSV:
  1. Compare its target branch (default "main") against the latest commit on the
     source repo's branch (default "main").
  2. If it is not behind, skip it.
  3. Otherwise create/update a "sync-<branch>" branch in the repo pointing at the
     upstream commit, and open a pull request from that branch into the target branch
     (or fast-forward the target branch directly when create_pr=False).

Usage:
    python3 gh_pr_create.py REPO_CSV REPO [--branch main] [--title TITLE]
                             [--repos ID [ID ...]] [-t TOKEN] [--csv]

    REPO_CSV    CSV file listing the repos to process. Must have (at least) the
                columns REPO_ID_SUFFIX, REPO_ID (owner/name) and REPO_HTTP, as
                produced by util.get_repos_from_csv().
    REPO        Upstream/source repo, in "owner/name" form, that all listed repos
                should be synced with.

Requires PyGithub (https://github.com/PyGithub/PyGithub) as the GitHub API client:

    python3 -m pip install PyGithub

PyGithub documentation: https://pygithub.readthedocs.io/en/latest/introduction.html
Other doc on PyGithub: https://www.thepythoncode.com/article/using-github-api-in-python

sync_fork() returns a (status, detail) tuple per repo, appended to a results list and,
if --csv is passed, written/appended to CSV_OUTPUT ("pr_create.csv"). Possible status
values: up_to_date, pr_created, pr_exists (an open sync PR was already there, skipped
to avoid duplicates), fast_forwarded, error_branch, error_pr, error_ff.
"""
__author__ = "Sebastian Sardina - ssardina - ssardina@gmail.com"
__copyright__ = "Copyright 2024-2025"

import csv
from argparse import ArgumentParser
import traceback

# https://pygithub.readthedocs.io/en/latest/introduction.html
from github import Github, GithubException

import util, utils_gh
from util import (
    TIMEZONE,
    NOW_ISO,
    NOW_TXT,
    add_csv,
)
SCRIPT_NAME = "gh_pr_feedback_create"

# setup my own logger for this script, using the slogger/loguru backend
from slogger.loguru_backend import logger, setup_logger

setup_logger(source=SCRIPT_NAME, timezone=TIMEZONE.key)


#####################################
# LOCAL GLOBAL VARIABLES FOR SCRIPT
#####################################

# Application global variables
CSV_OUTPUT = "pr_create.csv"
CSV_HEADER = ["REPO_ID_SUFFIX", "REPO_URL", "RESULT", "DETAILS"]

PR_TITLE = "Sync Assignment"
PR_MESSAGE = """
:wave:! This pull request was automatically generated by the instructor to sync with the upstream assignment repository.

Merge this pull request to sync your assignment repository with your instructor latest changes.

If you have any questions or concerns, please contact your instructor via the forum.

Attention: @{GH_USERNAME}
"""


def sync_fork(
    repo,   # fork repo (PyGitHub object)
    repo_source,  # upstream repo (PyGitHub object)
    source_branch="main",  # branch in upstream
    target_branch="main",  # branch in fork
    create_pr=False,  # if True, create PR instead of direct update
    pr_title=PR_TITLE,
    pr_message=PR_MESSAGE,
):
    """
    Sync repo (fork) from repo_source (upstream).

    Via ChatGPT: https://chatgpt.com/s/t_69cc800eb2d881919841d4dea86a6a06

    :return: (status, detail) tuple. status is one of "up_to_date", "pr_created",
        "pr_exists", "fast_forwarded", "error_branch", "error_pr", "error_ff".
    """

    logger.info(
        f"\n🔍 Comparing {repo.full_name}:{target_branch} "
        f"with {repo_source.full_name}:{source_branch}"
    , depth=1)

    # --- Step 1: Compare (correct cross-fork comparison)
    # compare = repo_source.compare(f"{repo.owner.login}:{target_branch}", source_branch)
    commit_source = repo_source.get_branch(source_branch).commit.sha
    compare = repo.compare(target_branch, commit_source)

    logger.info(f"Status: {compare.status}", depth=1)
    logger.info(f"Behind by: {compare.behind_by}, Ahead by: {compare.ahead_by}", depth=1)

    if compare.behind_by == 0:
        logger.info("✅ Fork is already up-to-date. Nothing to do.", depth=1)
        return "up_to_date", ""

    logger.info(f"⚠️ Fork is {compare.behind_by} commits behind upstream.", depth=1)

    # --- Step 2: Get latest upstream commit SHA
    source_sha = repo_source.get_branch(source_branch).commit.sha
    logger.info(f"Upstream latest SHA: {source_sha}")

    # --- Step 3: Create/update sync branch in fork
    sync_branch = f"sync-{source_branch}"

    try:
        ref = repo.get_git_ref(f"heads/{sync_branch}")
        logger.info(f"Updating existing branch {sync_branch}")
        ref.edit(source_sha, force=True)
    except GithubException as e:
        if e.status != 404:
            logger.error(f"❌ Failed to access branch {sync_branch}: {e}", depth=1)
            return "error_branch", str(e)
        logger.info(f"Creating new branch {sync_branch}")
        try:
            repo.create_git_ref(ref=f"refs/heads/{sync_branch}", sha=source_sha)
        except GithubException as e2:
            logger.error(f"❌ Failed to create branch {sync_branch}: {e2}", depth=1)
            return "error_branch", str(e2)

    # --- Step 4: Either create PR or fast-forward
    if create_pr:
        # skip if a sync PR is already open, to avoid piling up duplicates on reruns
        existing_prs = list(
            repo.get_pulls(state="open", head=f"{repo.owner.login}:{sync_branch}", base=target_branch)
        )
        if existing_prs:
            logger.info(f"ℹ️ Open PR already exists: {existing_prs[0].html_url}", depth=1)
            return "pr_exists", existing_prs[0].html_url

        logger.info("📬 Creating pull request...")

        try:
            pr = repo.create_pull(
                title=pr_title,
                body=pr_message.format(GH_USERNAME=repo.owner.login),
                head=sync_branch,
                base=target_branch,
            )
            logger.info(f"✅ PR created: {pr.html_url}", depth=1)
            return "pr_created", pr.html_url

        except GithubException as e:
            logger.error(f"❌ Failed to create PR: {e}", depth=1)
            return "error_pr", str(e)

    else:
        logger.info("⚡ Fast-forwarding branch directly...", depth=1)

        try:
            ref = repo.get_git_ref(f"heads/{target_branch}")
            ref.edit(source_sha, force=True)
            logger.info(f"✅ {target_branch} updated to upstream.", depth=1)
            return "fast_forwarded", target_branch

        except GithubException as e:
            logger.error(f"❌ Failed to update branch: {e}", depth=1)
            return "error_ff", str(e)


if __name__ == "__main__":
    parser = ArgumentParser(description="Merge PRs in multiple repos")
    parser.add_argument("REPO_CSV", help="List of repositories to get data from.")
    parser.add_argument(
        "REPO",
        help="Source repo for the pull request (Default: %(default)s).",
    )
    parser.add_argument(
        "--branch",
        default="main",
        help="Source branch for the pull request (Default: '%(default)s').",
    )
    parser.add_argument(
        "--title", 
        type=str,
        default=PR_TITLE,
        help="Title of the pull request (Default: '%(default)s').",
    )
    parser.add_argument(
        "--repos", nargs="+", help="if given, only the repos specified will be parsed."
    )
    parser.add_argument(
        "-t",
        "--token",
        # default=os.environ.get("GHTOKEN") or os.environ.get("GH_TOKEN"),
        help="File or string containing GitHub authorization token/password.",
    )
    parser.add_argument(
        "--csv",
        action="store_true",
        default=False,
        help="Dump results into CSV files (Default: %(default)s.)",
    )
    args = parser.parse_args()
    logger.info(f"Starting on {TIMEZONE}: {NOW_ISO} - {args}")

    ###############################################
    # Filter repos as desired
    ###############################################
    list_repos = util.get_repos_from_csv(args.REPO_CSV, args.repos)
    if len(list_repos) == 0:
        logger.error(f'No repos found in the mapping file "{args.REPO_CSV}". Stopping.')
        exit(0)

    ###############################################
    # Authenticate to GitHub
    ###############################################
    try:
        g = utils_gh.open_gitHub(token=args.token)
    except Exception as e:
        logger.error(
            "Something wrong happened during GitHub authentication. Check credentials."
        )
        traceback.print_exc()
        exit(1)

    ###############################################
    # Process each repo in list_repos
    ###############################################

    # this is the source repo for the PRs
    repo_source = g.get_repo(args.REPO)
    commit_source = repo_source.get_branch(args.branch).commit.sha
    logger.info(f"Source repo commit SHA: {commit_source}")

    no_repos = len(list_repos)
    output_csv = []
    for k, r in enumerate(list_repos, start=1):
        repo_no = r["NO"]
        repo_id = r["REPO_ID_SUFFIX"]
        repo_name = r["REPO_ID"]
        repo_url = r["REPO_HTTP"]
        logger.info(
            f"Processing repo {k}/{no_repos}: {repo_no}:{repo_id} ({repo_url})..."
        )

        repo = g.get_repo(repo_name)    # repo to create PR into (i.e., the student repo)

        status, detail = sync_fork(
            repo,  # fork repo (PyGitHub object)
            repo_source,  # upstream repo (PyGitHub object)
            source_branch=args.branch,  # branch in upstream
            target_branch=args.branch,  # branch in fork
            create_pr=True,  # if True, create PR instead of direct update
            pr_title=args.title,
        )
        output_csv.append([repo_id, repo_url, status, detail])

    # print summary stats
    no_errors = len([x for x in output_csv if str(x[2]).startswith("error")])
    logger.info(
        f"Finished! Total repos: {no_repos} - Processed: {len(output_csv)} - Errors: {no_errors}."
    )

    if args.csv:
        output_csv = sorted(output_csv, key=lambda x: x[2])
        add_csv(
            CSV_OUTPUT,
            CSV_HEADER,
            output_csv,
            append=True,
            timestamp=NOW_TXT,
            quoting=csv.QUOTE_NONNUMERIC
        )
        logger.info(f"Output written to CSV file: {CSV_OUTPUT}.")
